[package]
name = "test-bevy-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6" }
bevy_egui = { version = "0.12" }
colorsys = "0.6.5"
image = "0.24.1"
winit = "0.26.1"
